# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  schedule:
    - cron: "0 19 * * *"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      - name: OWASP ZAP Full Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          # GitHub Token to create issues in the repository
          token: ${{ github.token }}
          # Target URL
          target: https://maps-graphs-app-impressive-parrot-pn.app.cloud.gov/?page=facility-map
          # Relative path of the ZAP configuration file
          #rules_file_name: # optional
          # The Docker file to be executed
          #docker_name: # default is owasp/zap2docker-stable
          # Additional command line options
          #cmd_options: # optional
          # The title for the GitHub issue to be created
          #issue_title: # optional, default is ZAP Full Scan Report
          # The action status will be set to fail if ZAP identifies any alerts during the full scan
          #fail_action: # optional
          # Whether Github issues should be created or not
          #allow_issue_writing: # optional, default is true
      - name: OWASP ZAP Full Scan
        # You may pin to the exact commit or the version.
        # uses: zaproxy/action-full-scan@6eade0f93b10fad8cfb4e63b979703a2cbd0cc98
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          # GitHub Token to create issues in the repository
          token: ${{ github.token }}
          # Target URL
          target: https://maps-graphs-app-impressive-parrot-pn.app.cloud.gov/?page=program-insights
